FROM datajoint/djbase:py3.9-debian-8eb1715

# ARG GITHUB_USERNAME=datajoint # tried moving to ENV
USER anaconda:anaconda

COPY ./workflow-optogenetics/docker/apt_requirements.txt /tmp/
RUN /entrypoint.sh echo "Installed dependencies."

WORKDIR /main/workflow-optogenetics

# Always get interface/djarchive
RUN pip install --no-deps "element-interface@git+https://github.com/datajoint/element-interface"
RUN pip install --no-deps "djarchive-client@git+https://github.com/datajoint/djarchive-client"

# Always move local - conditional install in setup.sh
COPY --chown=anaconda:anaconda ./element-lab/ /main/element-lab/
COPY --chown=anaconda:anaconda ./element-animal/ /main/element-animal/
COPY --chown=anaconda:anaconda ./element-session/ /main/element-session/
COPY --chown=anaconda:anaconda ./element-event/ /main/element-event/
COPY --chown=anaconda:anaconda ./element-interface/ /main/element-interface/
COPY --chown=anaconda:anaconda ./element-optogenetics/ /main/element-optogenetics/
COPY --chown=anaconda:anaconda ./workflow-optogenetics/ /main/workflow-optogenetics/

# Conditional install - local-all, local-dlc, or git
COPY --chown=anaconda:anaconda ./workflow-optogenetics/docker/setup.sh /main/
COPY --chown=anaconda:anaconda ./workflow-optogenetics/docker/.env /main/
RUN chmod 755 /main/setup.sh
RUN chmod 755 /main/.env
RUN /main/setup.sh
RUN rm -f ./dj_local_conf.json
